
FROM eclipse-temurin:21-jdk AS build
WORKDIR /app


COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .
RUN ./mvnw dependency:go-offline -B


COPY src src
RUN ./mvnw clean package -DskipTests


FROM eclipse-temurin:21-jre
WORKDIR /app


COPY --from=build /app/target/quarkus-app /app/


ENV PORT=8080
EXPOSE 8080

# Comando de inicialização
CMD ["java", "-jar", "/app/quarkus-run.jar"]
